### ISSUE TITLE
List of Linea / EVM deviations

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/linea-tracer#315] opened 2023-11-06 11:02 UTC
- No tx's with to = precompile address allowed
- MODEXP doesn't allow for arguments with > 512 length (exponent, base, modulus)

**Comment by letypequividelespoubelles** [comment] 2024-08-16 13:25
duplicate of https://github.com/Consensys/linea-tracer/issues/315

**Closed by letypequividelespoubelles** 2024-08-16 13:25 UTC
Labels: documentation
